- name: Deploy the overcloud
  shell: |
    {{ working_dir }}/overcloud-deploy.sh > {{ deploy_log }} 2>&1
  when: step_deploy_overcloud

# we don't get a useful error code from the previous script, so check
# the log for a CREATE_FAILED message.
- name: Check overcloud deploy status
  command: >
    grep -q 'Stack overcloud CREATE_FAILED' {{ deploy_log }}
  register: deploy_result
  ignore_errors: true

- name: write out overcloud status to a file on the undercloud
  shell: >
    echo '{ "overcloud_deploy_result": "failed" }' > {{ local_working_dir }}/overcloud_deployment_result.json
  delegate_to: localhost
  when: deploy_result.rc != 0

- name: write out overcloud status to a file on the undercloud
  shell: >
    echo '{ "overcloud_deploy_result": "passed" }' > {{ local_working_dir }}/overcloud_deployment_result.json
  when: deploy_result.rc == 0

- name: import deployment status from file
  include_vars: {{ local_working_dir }}/overcloud_deployment_result.json

- name: echo deployment_status
  debug: var=overcloud_deploy_result


