- include: setup-heat-templates.yml
  when: undercloud_setup != "baremetal"
  tags:
    - overcloud-scripts

- include: create-scripts.yml
  tags:
    - overcloud-scripts

- include: deploy-overcloud.yml
  tags:
    - overcloud-deploy

- include: post-deploy.yml
  tags:
    - overcloud-post-deploy
