- name: set network_args fact for IPv4
  set_fact:
    network_args: >-
      -e {{overcloud_templates_path}}/environments/network-isolation.yaml
      -e {{overcloud_templates_path}}/environments/net-single-nic-with-vlans.yaml
      -e $HOME/network-environment.yaml
  when: network_isolation and not ipv6|bool|default(false)

- name: set network_args fact for IPv6
  set_fact:
    network_args: >-
      -e {{overcloud_templates_path}}/environments/network-isolation-v6.yaml
      -e /opt/stack/new/tripleo-ci/test-environments/ipv6-network-templates/network-environment.yaml
  when: network_isolation and ipv6|bool|default(false)

- name: enable pacemaker
  set_fact:
    pacemaker_args: >-
      -e {{overcloud_templates_path}}/environments/puppet-pacemaker.yaml
  when: enable_pacemaker

- name: disable L3 HA
  set_fact:
    pacemaker_args: >-
      {{ pacemaker_args }}
      -e $HOME/neutronl3ha.yaml
  when: enable_pacemaker and overcloud_nodes|length < 3
