- name: Copy the network-isolation parameters to the undercloud
  synchronize:
    src: "hardware_environments/{{ hw_env }}/network_configs/{{ network_isolation_type }}/{{ network_isolation_type }}.yml"
    dest: "{{ working_dir }}/network-environment.yaml"
    use_ssh_args: yes
  when: network_isolation

- name: Copy neutron l3 ha heat template
  when: enable_pacemaker and overcloud_nodes|length < 3
  template:
    src: "neutronl3ha.yaml.j2"
    dest: "{{ working_dir }}/neutronl3ha.yaml"
    mode: 0755
