- name: Copy the network-isolation parameters to the undercloud
  synchronize:
    src: "{{ local_heat_template_dir }}/hardware_environments/{{ hw_env }}/network_configs/{{ network_isolation_type }}/{{ network_isolation_type }}.yml"
    dest: "{{ working_dir }}/network-environment.yaml"
    use_ssh_args: yes
  when: network_isolation

- name: Setup controller net_config
  shell: |
    {{ working_dir }}/controller-net-config.sh > controller-net-config.log
  when: network_isolation
